name: Android CI

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Build Signed Release APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore_file: key-store.jks
        keystore_password: 666666
        key_alias: hiper-key
        key_password: 666666
        
    - name : upload apk
      uses: actions/upload-artifact@v3
      with:
        name: HiPer
        path: app/build/outputs/apk/release/app-release.apk
